name: ItemsAdderFix
version: ${project.version}
main: com.ssilensio.itemsadderfix.ItemsAdderFix
depend: [ProtocolLib]
loadbefore:
  - ItemsAdder
api-version: '1.20'
description: 'Normalizes hoverEvent entity ids to avoid JsonSyntaxException in ItemsAdder.'
author: ssilensio
